// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-92GvgWDhdf2GC0ytlfOEF1ICe6ztdP4',
    appId: '1:1048069060901:web:40bc34a0e5774e2b6202cc',
    messagingSenderId: '1048069060901',
    projectId: 'sport-house-9ba67',
    authDomain: 'sport-house-9ba67.firebaseapp.com',
    storageBucket: 'sport-house-9ba67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBguBpCpvoPI7J-KZrjnOQrIVpSyn1hqH4',
    appId: '1:1048069060901:android:6dcbb07b9b400d806202cc',
    messagingSenderId: '1048069060901',
    projectId: 'sport-house-9ba67',
    storageBucket: 'sport-house-9ba67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Uad_8trj8EPNCoHg5BY5U0w_uouZc5Q',
    appId: '1:1048069060901:ios:81edf401ab557e7d6202cc',
    messagingSenderId: '1048069060901',
    projectId: 'sport-house-9ba67',
    storageBucket: 'sport-house-9ba67.appspot.com',
    iosClientId: '1048069060901-s48va860gfqhrel69opucb4el7ieu571.apps.googleusercontent.com',
    iosBundleId: 'com.kingsleyTech.sportHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Uad_8trj8EPNCoHg5BY5U0w_uouZc5Q',
    appId: '1:1048069060901:ios:81edf401ab557e7d6202cc',
    messagingSenderId: '1048069060901',
    projectId: 'sport-house-9ba67',
    storageBucket: 'sport-house-9ba67.appspot.com',
    iosClientId: '1048069060901-s48va860gfqhrel69opucb4el7ieu571.apps.googleusercontent.com',
    iosBundleId: 'com.kingsleyTech.sportHouse',
  );
}
